#!/bin/env sh

# WORK IN PROGRESS

# setup net
# git, fetch dotfiles ...

pkg add wpa_supplicant 
pkg add NetworkManager

pkg add void-repo-nonfree-9_5                     

pkg add base-devel
pkg add coreutils 
pkg add bzip2 gzip unzip zip

pkg add alacritty 
pkg add direnv                        
pkg add firefox
pkg add fzf 
pkg add git
pkg add kitty kitty-terminfo
pkg add mpv 
pkg add nmap
pkg add sway swaybg swaylock
pkg add yt-dlp 

pkg add wireguard wireguard-dkms wireguard-tools            

pkg add erlang erlang-wx elixir

pkg add \
    postgresql-libs postgresql14 postgresql14-client \
    postgresql14-contrib postgresql14-doc

pkg add elogind                         
pkg add bluez
pkg add lua53
pkg add mesa mesa-dri mesa-opencl                      
pkg add wifi-firmware
pkg add wl-clipboard wlroots                          


pkg add cargo                            
pkg add dbus-devel                      
pkg add dbus-elogind                    
pkg add dbus-glib
pkg add dbus-libs                       
pkg add dbus-x11                        
pkg add findutils                         
pkg add fontconfig                       
pkg add fswatch                          
pkg add inetutils-hostname
pkg add inetutils-telnet
pkg add linux
pkg add linux-base                   
pkg add linux-firmware-amd-20211027_1             
pkg add linux-firmware-broadcom-20211027_1        
pkg add linux-firmware-intel-20211027_1           
pkg add linux-firmware-network-20211027_1         
pkg add linux-firmware-nvidia-20211027_1          
pkg add linux-headers
pkg add linux5.15                       
pkg add linux5.15-headers               
pkg add lm_sensors                        

pkg add cairo                            
pkg add LuaJIT
pkg add MesaLib-devel
pkg add PAmix
pkg add SDL2                             
pkg add SDL2-devel                       
pkg add SDL2_image                        
pkg add SDL2_image-devel                  
pkg add SDL2_ttf                         
pkg add SDL2_ttf-devel                   
pkg add Vulkan-Headers                  
pkg add acl                               
pkg add acpid                            
pkg add adwaita-icon-theme
pkg add alacritty-terminfo               
pkg add alsa-lib                        
pkg add alsa-lib-devel                  
pkg add alsa-pipewire                    
pkg add alsa-plugins-jack                 
pkg add alsa-plugins-pulseaudio           
pkg add alsa-ucm-conf                   
pkg add alsa-utils                        
pkg add android-tools
pkg add apulse                           
pkg add at-spi2-atk                      
pkg add at-spi2-atk-devel                
pkg add at-spi2-core                     
pkg add at-spi2-core-devel               
pkg add atk                              
pkg add atk-devel                        
pkg add attr                              
pkg add autoconf
pkg add automake                         
pkg add avahi-libs
pkg add base-files
pkg add base-system
pkg add bash-completion
pkg add basu                              
pkg add bc                               
pkg add bind-libs                       
pkg add bind-utils                      
pkg add binutils                         
pkg add binutils-doc                     
pkg add bison                             
pkg add brotli                            
pkg add brotli-devel                      
pkg add btrfs-progs                      
pkg add bubblewrap                        
pkg add bzip2-devel                       
pkg add c-ares                           
pkg add ca-certificates
pkg add cairo-devel                      
pkg add celt                             
pkg add clang                            
pkg add colord-devel                      
pkg add cpio
pkg add cryptsetup                        
pkg add cups-devel
pkg add curl                             
pkg add dash                           
pkg add dejavu-fonts-ttf
pkg add desktop-file-utils
pkg add device-mapper                  
pkg add dhcpcd                            
pkg add diffutils
pkg add dkms                              
pkg add dnssec-anchors
pkg add dosfstools
pkg add double-conversion                 
pkg add dracut
pkg add e2fsprogs                        
pkg add e2fsprogs-libs                   
pkg add ed
pkg add efibootmgr
pkg add electron13                       
pkg add elfutils-devel
pkg add enchant2                         
pkg add ethtool
pkg add eudev                            
pkg add eudev-libudev                    
pkg add eudev-libudev-devel              
pkg add exa                              
pkg add expat                             
pkg add expat-devel                       
pkg add f2fs-tools                       
pkg add faad2                            
pkg add feh
pkg add fftw-devel                       
pkg add file
pkg add flex                              
pkg add font-alias                        
pkg add font-util                         
pkg add fontconfig-devel                 
pkg add freefont-ttf
pkg add freetype                         
pkg add freetype-devel                   
pkg add fribidi                          
pkg add fribidi-devel                    
pkg add fuse                              
pkg add gawk                              
pkg add gcc
pkg add gdbm
pkg add gdk-pixbuf                       
pkg add gdk-pixbuf-devel                 
pkg add gettext
pkg add giflib                            
pkg add giflib-devel                      
pkg add gir-freedesktop                  
pkg add girara                            
pkg add github-cli                        
pkg add glib                             
pkg add glib-networking                  
pkg add glibc
pkg add glibc-devel
pkg add glibc-locales
pkg add glslang                       
pkg add glu                               
pkg add glu-devel                         
pkg add gmp                               
pkg add gnutls                            
pkg add graphene                         
pkg add graphite                         
pkg add graphite-devel                   
pkg add grep
pkg add grim                              
pkg add grimshot                          
pkg add groff                            
pkg add grub
pkg add grub-i386-efi
pkg add grub-x86_64-efi
pkg add gsettings-desktop-schemas
pkg add gst-plugins-base1                
pkg add gstreamer1                       
pkg add gtk+                            
pkg add gtk+3                           
pkg add gtk+3-devel                     
pkg add gtk-update-icon-cache           
pkg add gumbo-parser                     
pkg add harfbuzz-devel                    
pkg add hddtemp
pkg add hicolor-icon-theme
pkg add htop                              
pkg add httpie                            
pkg add hwids-20210613_1                          
pkg add hyphen                            
pkg add iana-etc-20211229_1                       
pkg add icu-devel
pkg add icu-libs
pkg add imlib2                            
pkg add inetutils-hostname
pkg add inetutils-telnet
pkg add inih-53_1                                 
pkg add inotify-tools                 
pkg add ipcalc
pkg add iperf3                           
pkg add iproute2                         
pkg add iptables                          
pkg add iputils-20211215_1                        
pkg add ipw2100-firmware
pkg add ipw2200-firmware
pkg add iso-codes                         
pkg add iw
pkg add iwd
pkg add jack                             
pkg add jansson
pkg add jbigkit-devel
pkg add jbigkit-libs
pkg add jq
pkg add json-c
pkg add kbd                               
pkg add kernel-libc-headers              
pkg add kmod
pkg add kpartx                            
pkg add lame
pkg add lcms2                            
pkg add lcms2-devel                      
pkg add ldb                               
pkg add libICE                           
pkg add libICE-devel                     
pkg add libOSMesa                        
pkg add libSM                             
pkg add libSM-devel                       
pkg add libX11                          
pkg add libX11-devel                    
pkg add libXScrnSaver                     
pkg add libXScrnSaver-devel               
pkg add libXau                            
pkg add libXau-devel                      
pkg add libXcomposite                     
pkg add libXcomposite-devel               
pkg add libXcursor                        
pkg add libXcursor-devel                  
pkg add libXdamage                        
pkg add libXdamage-devel                  
pkg add libXdmcp                          
pkg add libXdmcp-devel                    
pkg add libXext                           
pkg add libXext-devel                     
pkg add libXfixes                         
pkg add libXfixes-devel                   
pkg add libXfont2                         
pkg add libXfontcache                     
pkg add libXft                            
pkg add libXft-devel                      
pkg add libXi
pkg add libXi-devel
pkg add libXinerama                       
pkg add libXinerama-devel                 
pkg add libXmu                            
pkg add libXpm                           
pkg add libXrandr                         
pkg add libXrandr-devel                   
pkg add libXrender                       
pkg add libXrender-devel                 
pkg add libXt                             
pkg add libXtst                           
pkg add libXtst-devel                     
pkg add libXv                            
pkg add libXxf86misc                      
pkg add libXxf86vm                        
pkg add liba52                            
pkg add libaio                          
pkg add libaom                            
pkg add libarchive                        
pkg add libargon2
pkg add libaspell                        
pkg add libass                           
pkg add libasyncns
pkg add libasyncns-devel
pkg add libatomic
pkg add libavcodec                        
pkg add libavdevice                       
pkg add libavfilter                       
pkg add libavformat                       
pkg add libavresample                     
pkg add libavutil                         
pkg add libblkid                         
pkg add libblkid-devel                   
pkg add libbluray                         
pkg add libbs2b                           
pkg add libbsd                           
pkg add libcanberra
pkg add libcap
pkg add libcap-ng                         
pkg add libcap-progs
pkg add libcddb                           
pkg add libcdio                           
pkg add libcdio-paranoia
pkg add libcdparanoia
pkg add libclang                         
pkg add libclang-cpp                     
pkg add libclc                           
pkg add libcolord                         
pkg add libcrypto
pkg add libcryptsetup                     
pkg add libcups
pkg add libcurl                          
pkg add libdatrie                        
pkg add libdatrie-devel                  
pkg add libdav1d4                         
pkg add libdb                            
pkg add libdca                            
pkg add libdebuginfod
pkg add libdecor                          
pkg add libdecor-devel                    
pkg add libdjvulibre                     
pkg add libdrm                          
pkg add libdrm-devel                    
pkg add libdvbpsi                         
pkg add libdvdcss                         
pkg add libdvdnav                         
pkg add libdvdread                        
pkg add libebml                           
pkg add libedit                    
pkg add libefivar
pkg add libelf
pkg add libelogind                      
pkg add libepoxy                          
pkg add libepoxy-devel                    
pkg add libestr                          
pkg add libev
pkg add libev-devel
pkg add libevdev                         
pkg add libevent                         
pkg add libexif                          
pkg add libfastjson                      
pkg add libfdisk                         
pkg add libffi
pkg add libffi-devel
pkg add libfftw                          
pkg add libfixposix                       
pkg add libfixposix-devel                 
pkg add libfl-devel                       
pkg add libflac                           
pkg add libflac-devel                     
pkg add libfontenc                        
pkg add libfswatch                       
pkg add libgbm                           
pkg add libgbm-devel                     
pkg add libgcc
pkg add libgcc-devel
pkg add libgcrypt                         
pkg add libgfortran
pkg add libgirepository                  
pkg add libgirepository-devel            
pkg add libglapi                         
pkg add libglib-devel                    
pkg add libglvnd                          
pkg add libglvnd-devel                    
pkg add libgomp
pkg add libgpg-error
pkg add libgudev
pkg add libgusb                           
pkg add libharfbuzz                       
pkg add libhunspell
pkg add libical                          
pkg add libid3tag
pkg add libidn2                           
pkg add libinotify-tools              
pkg add libinput                         
pkg add libjack                          
pkg add libjbig2dec
pkg add libjpeg-turbo                     
pkg add libjpeg-turbo-devel               
pkg add libjpeg-turbo-tools               
pkg add libkmod
pkg add libldap                          
pkg add libldns                           
pkg add liblilv                         
pkg add libllvm12                        
pkg add libltdl                           
pkg add liblz4                            
pkg add liblzma                           
pkg add liblzma-devel                     
pkg add libmad
pkg add libmagic
pkg add libmanette                        
pkg add libmatroska                       
pkg add libmd                             
pkg add libmicrodns                       
pkg add libmm-glib                       
pkg add libmnl                            
pkg add libmodplug                      
pkg add libmount                         
pkg add libmount-devel                   
pkg add libmpcdec                         
pkg add libmpeg20                         
pkg add libmspack
pkg add libmtp                           
pkg add libndp
pkg add libnetfilter_conntrack            
pkg add libnfnetlink                      
pkg add libnftnl                          
pkg add libnl3                            
pkg add libnm                            
pkg add libnotify                         
pkg add libnuspell                        
pkg add libodbc                           
pkg add libogg                            
pkg add libogg-devel                      
pkg add libopenjpeg2                      
pkg add libpcap                          
pkg add libpciaccess
pkg add libpciaccess-devel
pkg add libpcre
pkg add libpcre2
pkg add libpcrecpp
pkg add libpipewire                      
pkg add libplacebo                      
pkg add libpng                           
pkg add libpng-devel                     
pkg add libpostproc                       
pkg add libprotobuf                      
pkg add libprotobuf-lite                 
pkg add libproxy                         
pkg add libpsl                           
pkg add libpsl-devel                     
pkg add libpulseaudio
pkg add libquadmath
pkg add libreadline8                    
pkg add librsvg                          
pkg add librsync                          
pkg add librtmp0                   
pkg add librubberband                     
pkg add libsamplerate                     
pkg add libsamplerate-devel               
pkg add libsasl                          
pkg add libseat                           
pkg add libseccomp                        
pkg add libsecret                        
pkg add libsensors                        
pkg add libserd                         
pkg add libsmartcols                     
pkg add libsndfile                       
pkg add libsndfile-devel                 
pkg add libsndio                          
pkg add libsodium                        
pkg add libsord                          
pkg add libsoup                          
pkg add libsoup-devel                    
pkg add libsoxr                           
pkg add libspeex                          
pkg add libssh                            
pkg add libssh2                           
pkg add libssl
pkg add libssp
pkg add libssp-devel
pkg add libstdc++
pkg add libstdc++-devel
pkg add libswresample                     
pkg add libswscale                        
pkg add libsynctex
pkg add libtasn1                         
pkg add libtdb                            
pkg add libthai                          
pkg add libthai-devel                    
pkg add libtheora                         
pkg add libtirpc                          
pkg add libtls                            
pkg add libtool                           
pkg add libunbound                       
pkg add libunistring                     
pkg add libupnp                          
pkg add libusb                           
pkg add libusb-compat                     
pkg add libusb-compat-devel               
pkg add libusb-devel                     
pkg add libuuid                          
pkg add libuuid-devel                    
pkg add libuv                            
pkg add libva                            
pkg add libvala                          
pkg add libvamp-plugin-sdk               
pkg add libvdpau
pkg add libvidstab                        
pkg add libvisual                         
pkg add libvlc                           
pkg add libvoikko
pkg add libvorbis                         
pkg add libvorbis-devel                   
pkg add libvpx6                           
pkg add libwacom
pkg add libwebp                           
pkg add libwebp-devel                     
pkg add libwoff2common1.0.2
pkg add libwoff2dec1.0.2
pkg add libwpe                           
pkg add libxatracker                     
pkg add libxbps                          
pkg add libxcb
pkg add libxcb-devel
pkg add libxkbcommon                      
pkg add libxkbcommon-devel                
pkg add libxkbcommon-x11                  
pkg add libxkbfile                        
pkg add libxkbregistry                    
pkg add libxml2                          
pkg add libxml2-devel                    
pkg add libxshmfence
pkg add libxslt                          
pkg add libxxHash                         
pkg add libzstd                           
pkg add libzstd-devel                     
pkg add live555                      
pkg add lmdb                             
pkg add lowdown                           
pkg add lsof                             
pkg add lua51-luafilesystem               
pkg add lua522                            
pkg add lua53                             
pkg add luakit
pkg add lvm2                           
pkg add lzo
pkg add lzo-devel
pkg add m4                               
pkg add make
pkg add mako
pkg add man-pages
pkg add man-pages-devel
pkg add man-pages-posix-2017a_5                   
pkg add mdadm
pkg add mdocml                           
pkg add mesa                             
pkg add mesa-dri                         
pkg add mesa-opencl                      
pkg add mit-krb5-libs                    
pkg add mkfontscale                       
pkg add mobile-broadband-provider-info
pkg add mozjs78                          
pkg add mtdev                             
pkg add mtr
pkg add ncurses
pkg add ncurses-base
pkg add ncurses-devel
pkg add ncurses-libs
pkg add nettle                            
pkg add newt                            
pkg add nghttp2                          
pkg add nghttp2-devel                    
pkg add nmap
pkg add nodejs                          
pkg add nspr
pkg add nss
pkg add nvi7                             
pkg add nyxt                              
pkg add ocl-icd                           
pkg add oniguruma
pkg add openblas                         
pkg add openbsd-netcat
pkg add openntpd
pkg add openresolv                       
pkg add openssh
pkg add openssl
pkg add openssl-devel
pkg add opus                              
pkg add opus-devel                        
pkg add orc                              
pkg add os-prober
pkg add p11-kit                         
pkg add pam                               
pkg add pam-base
pkg add pam-libs                          
pkg add pango                            
pkg add pango-devel                      
pkg add pango-xft                        
pkg add passwdqc                          
pkg add patch                             
pkg add pciutils                          
pkg add pcre-devel
pkg add perl                             
pkg add perl-Authen-SASL
pkg add perl-Convert-BinHex
pkg add perl-Digest-HMAC
pkg add perl-IO-Socket-SSL
pkg add perl-IO-stringy
pkg add perl-MIME-tools
pkg add perl-MailTools
pkg add perl-Net-SMTP-SSL
pkg add perl-Net-SSLeay
pkg add perl-TimeDate
pkg add perl-URI
pkg add perl-rename
pkg add pick                              
pkg add pipewire-devel                   
pkg add pixman                           
pkg add pixman-devel                     
pkg add pkg-config                       
pkg add polkit
pkg add popt
pkg add procps-ng                        
pkg add psmisc
pkg add pulseaudio
pkg add pulseaudio-devel
pkg add pulseaudio-utils
pkg add python3                          
pkg add python3-Pygments                 
pkg add python3-charset-normalizer       
pkg add python3-dbus                     
pkg add python3-defusedxml                
pkg add python3-idna
pkg add python3-pip                      
pkg add python3-pysocks                   
pkg add python3-requests                 
pkg add python3-requests-toolbelt         
pkg add python3-setuptools               
pkg add python3-six                      
pkg add python3-urllib3                  
pkg add qt5-core
pkg add qt5-dbus
pkg add qt5-gui
pkg add qt5-network
pkg add qt5-svg
pkg add qt5-widgets
pkg add qt5-x11extras
pkg add re2                          
pkg add rebar3                           
pkg add removed-packages
pkg add ripgrep                          
pkg add rlwrap                           
pkg add rsync                             
pkg add rsyslog                        
pkg add rtkit
pkg add run-parts                        
pkg add runit1                            
pkg add runit-void
pkg add rust                             
pkg add rust-std                         
pkg add samba-libs                      
pkg add sbc
pkg add seatd                             
pkg add shaderc
pkg add shadow                            
pkg add shared-mime-info
pkg add slang                             
pkg add slurp                             
pkg add snappy                            
pkg add sndio-devel                       
pkg add socklog                           
pkg add sof-firmware                      
pkg add spdx-licenses-list
pkg add speexdsp                          
pkg add sqlite                           
pkg add sqlite-devel                     
pkg add sratom                            
pkg add sudo
pkg add sway                              
pkg add swaybg
pkg add swaylock
pkg add taglib
pkg add talloc                            
pkg add tar
pkg add tcl                              
pkg add tevent                           
pkg add texinfo
pkg add the_silver_searcher               
pkg add thin-provisioning-tools           
pkg add thunderbird                      
pkg add tiff                              
pkg add tiff-devel                        
pkg add tk                               
pkg add traceroute                        
pkg add tree                              
pkg add tree-sitter                      
pkg add tslib
pkg add tzdata-2021e_1                            
pkg add uchardet                          
pkg add usbutils-014_1                            
pkg add util-linux                       
pkg add util-linux-common                
pkg add v4l-utils                        
pkg add vala                             
pkg add vala-devel                       
pkg add vim                            
pkg add vim-common                     
pkg add vlc                              
pkg add void-artwork
pkg add void-docs                    
pkg add void-docs-browse             
pkg add vscode                           
pkg add vulkan-loader                   
pkg add wayland                          
pkg add wayland-devel                    
pkg add wayland-protocols
pkg add webkit2gtk                       
pkg add webkit2gtk-devel                 
pkg add webrtc-audio-processing           
pkg add wget                             
pkg add which
pkg add wpebackend-fdo                    
pkg add wxWidgets                       
pkg add wxWidgets-common                
pkg add x264
pkg add x265
pkg add xbps                             
pkg add xbps-triggers
pkg add xcb-proto                        
pkg add xcb-util                          
pkg add xcb-util-errors
pkg add xcb-util-image                    
pkg add xcb-util-keysyms                  
pkg add xcb-util-renderutil               
pkg add xcb-util-wm                       
pkg add xclip
pkg add xdg-dbus-proxy                    
pkg add xdg-utils                         
pkg add xfsprogs                         
pkg add xkbcomp                           
pkg add xkeyboard-config                 
pkg add xorg-server-common               
pkg add xorg-server-xwayland             
pkg add xorgproto
pkg add xset                              
pkg add xtools
pkg add xtrans                            
pkg add xvidcore                          
pkg add xxd                            
pkg add xz                                
pkg add zd1211-firmware
pkg add zlib                             
pkg add zlib-devel                       
