--# deps: (mkdir, ag, fzf, git, gcc, libstdc++, python 3)

require('options')
require('packages')
require('autocommands')
require('autosave')
require('keys')
require('statusline')
require('tabline')
require('fzf_config')
require('gitsigns_config')
require('lsp_config')
require('netrw_config')
require('peekaboo_config')
require('colors')

-- require('treesitter_config')
-- require('vlime_config')
